<?php
$content = <<<'EOT'
<?php

namespace App\Console\Commands;

use App\Jobs\ProcessWaterLevelEvent;
use App\Jobs\ProcessWeatherEvent;
use App\Services\SqsQueueService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class BulkQueueWorker extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:bulk-queue-worker {--max-messages=10 : The maximum number of messages to retrieve per batch} {--sleep=3 : Number of seconds to sleep when no job is available} {--once : Only run the worker once for tests}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run a worker to process SQS messages in bulk';

    protected SqsQueueService $sqsService;

    public function __construct(SqsQueueService $sqsService)
    {
        parent::__construct();
        $this->sqsService = $sqsService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting bulk queue worker...');

        $waterQueueUrl = config('services.sqs.water_level_queue', env('AWS_SQS_WATER_LEVEL_QUEUE_URL', ''));
        $weatherQueueUrl = config('services.sqs.weather_queue', env('AWS_SQS_WEATHER_QUEUE_URL', ''));

        if (empty($waterQueueUrl) && empty($weatherQueueUrl)) {
            $this->error('Neither water level nor weather SQS queue URL is configured.');
            return;
        }

        $maxMessages = (int) $this->option('max-messages');
        $sleep = (int) $this->option('sleep');
        $once = $this->option('once');

        while (true) {
            $processedAny = false;

            if (!empty($waterQueueUrl)) {
                $processedAny = $this->processQueue($waterQueueUrl, ProcessWaterLevelEvent::class, $maxMessages) || $processedAny;
            }

            if (!empty($weatherQueueUrl)) {
                $processedAny = $this->processQueue($weatherQueueUrl, ProcessWeatherEvent::class, $maxMessages) || $processedAny;
            }

            if ($once) {
                break;
            }

            if (!$processedAny) {
                // If no messages were processed in either queue, sleep to avoid busy looping
                sleep($sleep);
            }
        }
    }

    /**
     * Poll a queue and process its messages in bulk.
     *
     * @param string $queueUrl
     * @param string $jobClass
     * @param int $maxMessages
     * @return bool True if messages were processed, false otherwise.
     */
    protected function processQueue(string $queueUrl, string $jobClass, int $maxMessages): bool
    {
        $messages = $this->sqsService->receiveMessageBatch($queueUrl, $maxMessages);

        if (empty($messages)) {
            return false;
        }

        $receiptHandles = [];
        $eventDataBatch = [];

        foreach ($messages as $message) {
            $body = json_decode($message['Body'], true);

            if ($body) {
                if (isset($body['job']) && isset($body['data']['commandName'])) {
                     $command = unserialize($body['data']['command']);
                     // Extract property data via reflection or assume it exposes a public method
                     // For our test, the load test sends the array directly without wrapping in a Job
                     // So we prioritize raw SQS messages generated by our poller.
                     // But if needed, can extract $command->data
                } elseif (isset($body['station_code'])) {
                    $eventDataBatch[] = $body;
                } elseif (isset($body['data']) && is_array($body['data']) && isset($body['data']['station_code'])) {
                    $eventDataBatch[] = $body['data']; // Sometimes queued jobs have body->data
                }
            }

            $receiptHandles[] = $message['ReceiptHandle'];
        }

        if (!empty($eventDataBatch)) {
            try {
                // Instantiate the job with the bulk data and handle it synchronously
                $job = new $jobClass($eventDataBatch);
                $job->handle();

                // Delete the processed messages
                $this->sqsService->deleteMessageBatch($queueUrl, $receiptHandles);

                $this->info("Processed batch of " . count($eventDataBatch) . " messages from " . basename($queueUrl));
                return true;
            } catch (\Exception $e) {
                Log::error("Failed to process bulk job {$jobClass}: " . $e->getMessage());
                $this->error("Failed to process bulk job {$jobClass}: " . $e->getMessage());
                // Do not delete messages on failure so they can be retried
                return false;
            }
        } else {
             // Messages received but couldn't be parsed
             $this->sqsService->deleteMessageBatch($queueUrl, $receiptHandles);
             return true;
        }
    }
}
EOT;
file_put_contents('src/app/Console/Commands/BulkQueueWorker.php', $content);
